name: Audiobookshelf
version: 2.24.0b11
slug: audiobookshelf
description: Self-hosted audiobook and podcast server
url: https://github.com/your-username/hassio-audiobookshelf
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
startup: services
boot: auto
init: false
map:
  - share:rw
  - config:rw
  - media:rw
ports:
  13378/tcp: null
ports_description:
  13378/tcp: Web interface (disabled when using ingress)
ingress: true
ingress_port: 13378
panel_icon: mdi:book-open-page-variant
panel_title: Audiobookshelf
panel_admin: false
options:
  log_level: info
  ssl: false
  certfile: fullchain.pem
  keyfile: privkey.pem
  external_access: false
  audiobooks_path: /share/audiobooks
  podcasts_path: /share/podcasts
  create_folders: true
schema:
  log_level: match(^(trace|debug|info|warn|error|fatal|off)$)
  ssl: bool
  certfile: str
  keyfile: str
  external_access: bool
  audiobooks_path: str
  podcasts_path: str
  create_folders: bool
image: ghcr.io/advplyr/audiobookshelf:{arch}-{version}